/* AUTOMATICALLY GENERATED CODE DO NOT MODIFY */
/*   To generate run: "serverpod generate"    */

// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: public_member_api_docs
// ignore_for_file: type_literal_in_constant_pattern
// ignore_for_file: use_super_parameters
// ignore_for_file: invalid_use_of_internal_member

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:serverpod_auth_idp_client/serverpod_auth_idp_client.dart'
    as _i1;
import 'package:serverpod_client/serverpod_client.dart' as _i2;
import 'dart:async' as _i3;
import 'package:serverpod_auth_core_client/serverpod_auth_core_client.dart'
    as _i4;
import 'package:serverpod_auth_client/serverpod_auth_client.dart' as _i5;
import 'package:cine_pass_client/src/protocol/cine_pass/film_response.dart'
    as _i6;
import 'package:cine_pass_client/src/protocol/cine_pass/seance_response.dart'
    as _i7;
import 'package:cine_pass_client/src/protocol/cine_pass/cinema_response.dart'
    as _i8;
import 'package:cine_pass_client/src/protocol/cine_pass/event_response.dart'
    as _i9;
import 'package:cine_pass_client/src/protocol/greetings/greeting.dart' as _i10;
import 'protocol.dart' as _i11;

/// Exposes Google sign-in methods to the client.
/// {@category Endpoint}
class EndpointGoogleIdp extends _i1.EndpointGoogleIdpBase {
  EndpointGoogleIdp(_i2.EndpointCaller caller) : super(caller);

  @override
  String get name => 'googleIdp';

  /// Validates a Google ID token and either logs in the associated user or
  /// creates a new user account if the Google account ID is not yet known.
  ///
  /// If a new user is created an associated [UserProfile] is also created.
  @override
  _i3.Future<_i4.AuthSuccess> login({
    required String idToken,
    required String? accessToken,
  }) => caller.callServerEndpoint<_i4.AuthSuccess>(
    'googleIdp',
    'login',
    {
      'idToken': idToken,
      'accessToken': accessToken,
    },
  );

  @override
  _i3.Future<bool> hasAccount() => caller.callServerEndpoint<bool>(
    'googleIdp',
    'hasAccount',
    {},
  );
}

/// By extending [RefreshJwtTokensEndpoint], the JWT token refresh endpoint
/// is made available on the server and enables automatic token refresh on the client.
/// {@category Endpoint}
class EndpointJwtRefresh extends _i4.EndpointRefreshJwtTokens {
  EndpointJwtRefresh(_i2.EndpointCaller caller) : super(caller);

  @override
  String get name => 'jwtRefresh';

  /// Creates a new token pair for the given [refreshToken].
  ///
  /// Can throw the following exceptions:
  /// -[RefreshTokenMalformedException]: refresh token is malformed and could
  ///   not be parsed. Not expected to happen for tokens issued by the server.
  /// -[RefreshTokenNotFoundException]: refresh token is unknown to the server.
  ///   Either the token was deleted or generated by a different server.
  /// -[RefreshTokenExpiredException]: refresh token has expired. Will happen
  ///   only if it has not been used within configured `refreshTokenLifetime`.
  /// -[RefreshTokenInvalidSecretException]: refresh token is incorrect, meaning
  ///   it does not refer to the current secret refresh token. This indicates
  ///   either a malfunctioning client or a malicious attempt by someone who has
  ///   obtained the refresh token. In this case the underlying refresh token
  ///   will be deleted, and access to it will expire fully when the last access
  ///   token is elapsed.
  ///
  /// This endpoint is unauthenticated, meaning the client won't include any
  /// authentication information with the call.
  @override
  _i3.Future<_i4.AuthSuccess> refreshAccessToken({
    required String refreshToken,
  }) => caller.callServerEndpoint<_i4.AuthSuccess>(
    'jwtRefresh',
    'refreshAccessToken',
    {'refreshToken': refreshToken},
    authenticated: false,
  );
}

/// {@category Endpoint}
class EndpointPhoneAuth extends _i2.EndpointRef {
  EndpointPhoneAuth(_i2.EndpointCaller caller) : super(caller);

  @override
  String get name => 'phoneAuth';

  _i3.Future<void> sendVerificationCode(String phoneNumber) =>
      caller.callServerEndpoint<void>(
        'phoneAuth',
        'sendVerificationCode',
        {'phoneNumber': phoneNumber},
        authenticated: false,
      );

  _i3.Future<_i5.AuthKey?> verifyCode(
    String phoneNumber,
    String code,
  ) => caller.callServerEndpoint<_i5.AuthKey?>(
    'phoneAuth',
    'verifyCode',
    {
      'phoneNumber': phoneNumber,
      'code': code,
    },
    authenticated: false,
  );
}

/// Endpoint CinePass : films, séances, cinémas, événements (données BDD).
/// {@category Endpoint}
class EndpointCinePass extends _i2.EndpointRef {
  EndpointCinePass(_i2.EndpointCaller caller) : super(caller);

  @override
  String get name => 'cinePass';

  /// Liste de tous les films.
  _i3.Future<List<_i6.FilmResponse>> getFilms() =>
      caller.callServerEndpoint<List<_i6.FilmResponse>>(
        'cinePass',
        'getFilms',
        {},
      );

  /// Détail d'un film par id.
  _i3.Future<_i6.FilmResponse?> getFilmById(String id) =>
      caller.callServerEndpoint<_i6.FilmResponse?>(
        'cinePass',
        'getFilmById',
        {'id': id},
      );

  /// Séances pour un film (avec nom cinéma, salle, ville).
  _i3.Future<List<_i7.SeanceResponse>> getSeancesForFilm(String filmId) =>
      caller.callServerEndpoint<List<_i7.SeanceResponse>>(
        'cinePass',
        'getSeancesForFilm',
        {'filmId': filmId},
      );

  /// Liste des cinémas.
  _i3.Future<List<_i8.CinemaResponse>> getCinemas() =>
      caller.callServerEndpoint<List<_i8.CinemaResponse>>(
        'cinePass',
        'getCinemas',
        {},
      );

  /// Liste des événements à venir.
  _i3.Future<List<_i9.EventResponse>> getEvents() =>
      caller.callServerEndpoint<List<_i9.EventResponse>>(
        'cinePass',
        'getEvents',
        {},
      );

  /// Détail d'un événement par id.
  _i3.Future<_i9.EventResponse?> getEventById(String id) =>
      caller.callServerEndpoint<_i9.EventResponse?>(
        'cinePass',
        'getEventById',
        {'id': id},
      );

  /// Villes distinctes (films + événements) pour les filtres.
  _i3.Future<List<String>> getCities() =>
      caller.callServerEndpoint<List<String>>(
        'cinePass',
        'getCities',
        {},
      );

  /// Genres distincts (films) pour les filtres.
  _i3.Future<List<String>> getGenres() =>
      caller.callServerEndpoint<List<String>>(
        'cinePass',
        'getGenres',
        {},
      );

  /// Catégories d'événements pour les filtres.
  _i3.Future<List<String>> getEventCategories() =>
      caller.callServerEndpoint<List<String>>(
        'cinePass',
        'getEventCategories',
        {},
      );
}

/// This is an example endpoint that returns a greeting message through
/// its [hello] method.
/// {@category Endpoint}
class EndpointGreeting extends _i2.EndpointRef {
  EndpointGreeting(_i2.EndpointCaller caller) : super(caller);

  @override
  String get name => 'greeting';

  /// Returns a personalized greeting message: "Hello {name}".
  _i3.Future<_i10.Greeting> hello(String name) =>
      caller.callServerEndpoint<_i10.Greeting>(
        'greeting',
        'hello',
        {'name': name},
      );
}

class Modules {
  Modules(Client client) {
    auth = _i5.Caller(client);
    serverpod_auth_idp = _i1.Caller(client);
    serverpod_auth_core = _i4.Caller(client);
  }

  late final _i5.Caller auth;

  late final _i1.Caller serverpod_auth_idp;

  late final _i4.Caller serverpod_auth_core;
}

class Client extends _i2.ServerpodClientShared {
  Client(
    String host, {
    dynamic securityContext,
    @Deprecated(
      'Use authKeyProvider instead. This will be removed in future releases.',
    )
    super.authenticationKeyManager,
    Duration? streamingConnectionTimeout,
    Duration? connectionTimeout,
    Function(
      _i2.MethodCallContext,
      Object,
      StackTrace,
    )?
    onFailedCall,
    Function(_i2.MethodCallContext)? onSucceededCall,
    bool? disconnectStreamsOnLostInternetConnection,
  }) : super(
         host,
         _i11.Protocol(),
         securityContext: securityContext,
         streamingConnectionTimeout: streamingConnectionTimeout,
         connectionTimeout: connectionTimeout,
         onFailedCall: onFailedCall,
         onSucceededCall: onSucceededCall,
         disconnectStreamsOnLostInternetConnection:
             disconnectStreamsOnLostInternetConnection,
       ) {
    googleIdp = EndpointGoogleIdp(this);
    jwtRefresh = EndpointJwtRefresh(this);
    phoneAuth = EndpointPhoneAuth(this);
    cinePass = EndpointCinePass(this);
    greeting = EndpointGreeting(this);
    modules = Modules(this);
  }

  late final EndpointGoogleIdp googleIdp;

  late final EndpointJwtRefresh jwtRefresh;

  late final EndpointPhoneAuth phoneAuth;

  late final EndpointCinePass cinePass;

  late final EndpointGreeting greeting;

  late final Modules modules;

  @override
  Map<String, _i2.EndpointRef> get endpointRefLookup => {
    'googleIdp': googleIdp,
    'jwtRefresh': jwtRefresh,
    'phoneAuth': phoneAuth,
    'cinePass': cinePass,
    'greeting': greeting,
  };

  @override
  Map<String, _i2.ModuleEndpointCaller> get moduleLookup => {
    'auth': modules.auth,
    'serverpod_auth_idp': modules.serverpod_auth_idp,
    'serverpod_auth_core': modules.serverpod_auth_core,
  };
}
