-- OBSOLÈTE — tout est fusionné dans `cine_pass_schema.sql` (événements + détails par type + index + vue).
-- Ne plus maintenir ce fichier ; le conserver évite les liens cassés dans d’anciennes docs.
